function renderGridMockDataModule(){

  this.getMocks = function(){
    return [{
      id: 0,
      dropTime: '10/1/16 11:22',
      name: 'pre-render',
      pack: null,
      rate: null,
      user: 'sky',
      status: { state: 'prerender' },
      actions: 'prerender',
    },{
      id: 1,
      dropTime: '10/15/16 5:02',
      name: 'rendering',
      pack: 'Ghost Voices',
      rate: 44000,
      user: 'sky',
      status: { state: 'rendering', progress: 58 },
      actions: 'rendering',
    },{
      id: 2,
      dropTime: '10/6/16 1:20',
      name: 'post-render',
      pack: 'Tera Piano',
      rate: 24000,
      user: 'sky',
      status: { state: 'postrender', time: '3 minutes' },
      actions: 'postrender',
    }];
  }

  this.getMocksTable = function(){
    return [{
      "id": 1,
      "gender": "Male",
      "first_name": "Samuel",
      "last_name": "Gordon",
      "email": "sgordon0@gov.uk",
      "ip_address": "139.20.134.94"
    }, {
      "id": 2,
      "gender": "Female",
      "first_name": "Mildred",
      "last_name": "Elliott",
      "email": "melliott1@apache.org",
      "ip_address": "218.140.149.173"
    }, {
      "id": 3,
      "gender": "Female",
      "first_name": "Kathy",
      "last_name": "Gilbert",
      "email": "kgilbert2@cbsnews.com",
      "ip_address": "241.36.180.3"
    }, {
      "id": 4,
      "gender": "Male",
      "first_name": "Phillip",
      "last_name": "Freeman",
      "email": "pfreeman3@1und1.de",
      "ip_address": "209.103.3.141"
    }, {
      "id": 5,
      "gender": "Male",
      "first_name": "John",
      "last_name": "Young",
      "email": "jyoung4@uiuc.edu",
      "ip_address": "205.208.61.191"
    }, {
      "id": 6,
      "gender": "Male",
      "first_name": "Charles",
      "last_name": "Brooks",
      "email": "cbrooks5@independent.co.uk",
      "ip_address": "143.189.119.150"
    }, {
      "id": 7,
      "gender": "Male",
      "first_name": "Phillip",
      "last_name": "Coleman",
      "email": "pcoleman6@lulu.com",
      "ip_address": "241.183.93.232"
    }, {
      "id": 8,
      "gender": "Female",
      "first_name": "Mildred",
      "last_name": "Howell",
      "email": "mhowell7@discuz.net",
      "ip_address": "162.63.202.224"
    }, {
      "id": 9,
      "gender": "Female",
      "first_name": "Lisa",
      "last_name": "Ross",
      "email": "lross8@people.com.cn",
      "ip_address": "200.9.17.58"
    }, {
      "id": 10,
      "gender": "Male",
      "first_name": "Steven",
      "last_name": "Washington",
      "email": "swashington9@reuters.com",
      "ip_address": "12.115.19.205"
    }, {
      "id": 11,
      "gender": "Female",
      "first_name": "Norma",
      "last_name": "Perry",
      "email": "nperrya@woothemes.com",
      "ip_address": "131.141.99.55"
    }, {
      "id": 12,
      "gender": "Female",
      "first_name": "Bonnie",
      "last_name": "Hanson",
      "email": "bhansonb@google.com",
      "ip_address": "156.88.144.27"
    }, {
      "id": 13,
      "gender": "Male",
      "first_name": "Raymond",
      "last_name": "Roberts",
      "email": "rrobertsc@go.com",
      "ip_address": "166.74.8.77"
    }, {
      "id": 14,
      "gender": "Male",
      "first_name": "Nicholas",
      "last_name": "Berry",
      "email": "nberryd@tmall.com",
      "ip_address": "67.138.218.139"
    }, {
      "id": 15,
      "gender": "Male",
      "first_name": "Raymond",
      "last_name": "Ramos",
      "email": "rramose@pcworld.com",
      "ip_address": "153.210.114.209"
    }, {
      "id": 16,
      "gender": "Female",
      "first_name": "Jennifer",
      "last_name": "George",
      "email": "jgeorgef@about.me",
      "ip_address": "138.237.24.21"
    }, {
      "id": 17,
      "gender": "Female",
      "first_name": "Sara",
      "last_name": "Hayes",
      "email": "shayesg@huffingtonpost.com",
      "ip_address": "229.220.51.98"
    }, {
      "id": 18,
      "gender": "Female",
      "first_name": "Linda",
      "last_name": "Little",
      "email": "llittleh@blog.com",
      "ip_address": "3.46.116.14"
    }, {
      "id": 19,
      "gender": "Female",
      "first_name": "Jessica",
      "last_name": "Warren",
      "email": "jwarreni@oaic.gov.au",
      "ip_address": "59.142.169.184"
    }, {
      "id": 20,
      "gender": "Female",
      "first_name": "Rebecca",
      "last_name": "Hill",
      "email": "rhillj@state.gov",
      "ip_address": "170.171.72.78"
    }, {
      "id": 21,
      "gender": "Female",
      "first_name": "Virginia",
      "last_name": "Moreno",
      "email": "vmorenok@who.int",
      "ip_address": "133.214.242.41"
    }, {
      "id": 22,
      "gender": "Female",
      "first_name": "Mary",
      "last_name": "Romero",
      "email": "mromerol@wired.com",
      "ip_address": "190.77.89.17"
    }, {
      "id": 23,
      "gender": "Female",
      "first_name": "Angela",
      "last_name": "Nelson",
      "email": "anelsonm@vk.com",
      "ip_address": "211.253.185.3"
    }, {
      "id": 24,
      "gender": "Female",
      "first_name": "Amanda",
      "last_name": "Nelson",
      "email": "anelsonn@networkadvertising.org",
      "ip_address": "22.26.21.244"
    }, {
      "id": 25,
      "gender": "Female",
      "first_name": "Jennifer",
      "last_name": "Perez",
      "email": "jperezo@t-online.de",
      "ip_address": "234.172.209.68"
    }, {
      "id": 26,
      "gender": "Male",
      "first_name": "George",
      "last_name": "Dunn",
      "email": "gdunnp@upenn.edu",
      "ip_address": "216.70.48.111"
    }, {
      "id": 27,
      "gender": "Female",
      "first_name": "Frances",
      "last_name": "Ross",
      "email": "frossq@tiny.cc",
      "ip_address": "210.4.21.247"
    }, {
      "id": 28,
      "gender": "Female",
      "first_name": "Rebecca",
      "last_name": "Perkins",
      "email": "rperkinsr@hp.com",
      "ip_address": "67.225.2.101"
    }, {
      "id": 29,
      "gender": "Male",
      "first_name": "Charles",
      "last_name": "Stephens",
      "email": "cstephenss@eventbrite.com",
      "ip_address": "217.243.0.96"
    }, {
      "id": 30,
      "gender": "Male",
      "first_name": "Victor",
      "last_name": "Ross",
      "email": "vrosst@toplist.cz",
      "ip_address": "50.110.157.12"
    }, {
      "id": 31,
      "gender": "Male",
      "first_name": "Carl",
      "last_name": "Warren",
      "email": "cwarrenu@altervista.org",
      "ip_address": "78.216.207.166"
    }, {
      "id": 32,
      "gender": "Male",
      "first_name": "Arthur",
      "last_name": "Nelson",
      "email": "anelsonv@woothemes.com",
      "ip_address": "98.12.157.58"
    }, {
      "id": 33,
      "gender": "Female",
      "first_name": "Nancy",
      "last_name": "Richards",
      "email": "nrichardsw@noaa.gov",
      "ip_address": "174.111.144.247"
    }, {
      "id": 34,
      "gender": "Female",
      "first_name": "Ashley",
      "last_name": "Welch",
      "email": "awelchx@bing.com",
      "ip_address": "36.220.254.127"
    }, {
      "id": 35,
      "gender": "Female",
      "first_name": "Carolyn",
      "last_name": "Mason",
      "email": "cmasony@cargocollective.com",
      "ip_address": "187.101.115.196"
    }, {
      "id": 36,
      "gender": "Female",
      "first_name": "Sharon",
      "last_name": "Murphy",
      "email": "smurphyz@hubpages.com",
      "ip_address": "60.150.186.60"
    }, {
      "id": 37,
      "gender": "Male",
      "first_name": "Nicholas",
      "last_name": "Wood",
      "email": "nwood10@ehow.com",
      "ip_address": "203.180.79.133"
    }, {
      "id": 38,
      "gender": "Male",
      "first_name": "Martin",
      "last_name": "Romero",
      "email": "mromero11@marriott.com",
      "ip_address": "20.131.243.82"
    }, {
      "id": 39,
      "gender": "Male",
      "first_name": "Antonio",
      "last_name": "Morrison",
      "email": "amorrison12@oakley.com",
      "ip_address": "113.26.101.172"
    }, {
      "id": 40,
      "gender": "Female",
      "first_name": "Pamela",
      "last_name": "Morgan",
      "email": "pmorgan13@netscape.com",
      "ip_address": "170.68.86.242"
    }, {
      "id": 41,
      "gender": "Male",
      "first_name": "Earl",
      "last_name": "Murphy",
      "email": "emurphy14@illinois.edu",
      "ip_address": "177.204.142.148"
    }, {
      "id": 42,
      "gender": "Male",
      "first_name": "Paul",
      "last_name": "Roberts",
      "email": "proberts15@shareasale.com",
      "ip_address": "70.236.202.232"
    }, {
      "id": 43,
      "gender": "Male",
      "first_name": "Aaron",
      "last_name": "Day",
      "email": "aday16@disqus.com",
      "ip_address": "48.40.169.181"
    }, {
      "id": 44,
      "gender": "Female",
      "first_name": "Carol",
      "last_name": "Williams",
      "email": "cwilliams17@google.com.hk",
      "ip_address": "167.126.38.144"
    }, {
      "id": 45,
      "gender": "Male",
      "first_name": "Jerry",
      "last_name": "Hart",
      "email": "jhart18@cam.ac.uk",
      "ip_address": "147.152.52.122"
    }, {
      "id": 46,
      "gender": "Male",
      "first_name": "Patrick",
      "last_name": "Lee",
      "email": "plee19@etsy.com",
      "ip_address": "21.55.186.62"
    }, {
      "id": 47,
      "gender": "Female",
      "first_name": "Betty",
      "last_name": "Banks",
      "email": "bbanks1a@creativecommons.org",
      "ip_address": "66.2.228.160"
    }, {
      "id": 48,
      "gender": "Female",
      "first_name": "Stephanie",
      "last_name": "Carr",
      "email": "scarr1b@unc.edu",
      "ip_address": "185.209.242.206"
    }, {
      "id": 49,
      "gender": "Female",
      "first_name": "Kathryn",
      "last_name": "Austin",
      "email": "kaustin1c@ebay.com",
      "ip_address": "178.179.224.56"
    }, {
      "id": 50,
      "gender": "Male",
      "first_name": "Chris",
      "last_name": "Andrews",
      "email": "candrews1d@homestead.com",
      "ip_address": "52.106.6.193"
    }, {
      "id": 51,
      "gender": "Male",
      "first_name": "Kevin",
      "last_name": "Lee",
      "email": "klee1e@jigsy.com",
      "ip_address": "55.109.248.42"
    }, {
      "id": 52,
      "gender": "Female",
      "first_name": "Donna",
      "last_name": "Lopez",
      "email": "dlopez1f@archive.org",
      "ip_address": "131.244.196.0"
    }, {
      "id": 53,
      "gender": "Male",
      "first_name": "Frank",
      "last_name": "White",
      "email": "fwhite1g@tuttocitta.it",
      "ip_address": "126.210.30.193"
    }, {
      "id": 54,
      "gender": "Female",
      "first_name": "Michelle",
      "last_name": "Grant",
      "email": "mgrant1h@dmoz.org",
      "ip_address": "239.149.167.20"
    }, {
      "id": 55,
      "gender": "Female",
      "first_name": "Bonnie",
      "last_name": "Knight",
      "email": "bknight1i@timesonline.co.uk",
      "ip_address": "97.206.0.62"
    }, {
      "id": 56,
      "gender": "Male",
      "first_name": "David",
      "last_name": "Lawson",
      "email": "dlawson1j@csmonitor.com",
      "ip_address": "171.24.4.197"
    }, {
      "id": 57,
      "gender": "Male",
      "first_name": "Matthew",
      "last_name": "Alexander",
      "email": "malexander1k@yolasite.com",
      "ip_address": "175.40.150.211"
    }, {
      "id": 58,
      "gender": "Male",
      "first_name": "Paul",
      "last_name": "Knight",
      "email": "pknight1l@weebly.com",
      "ip_address": "103.125.152.150"
    }, {
      "id": 59,
      "gender": "Male",
      "first_name": "Chris",
      "last_name": "Young",
      "email": "cyoung1m@wiley.com",
      "ip_address": "18.69.31.52"
    }, {
      "id": 60,
      "gender": "Female",
      "first_name": "Susan",
      "last_name": "Riley",
      "email": "sriley1n@paypal.com",
      "ip_address": "82.185.249.111"
    }, {
      "id": 61,
      "gender": "Female",
      "first_name": "Theresa",
      "last_name": "Wagner",
      "email": "twagner1o@examiner.com",
      "ip_address": "194.56.30.173"
    }, {
      "id": 62,
      "gender": "Female",
      "first_name": "Martha",
      "last_name": "Cooper",
      "email": "mcooper1p@list-manage.com",
      "ip_address": "221.59.20.63"
    }, {
      "id": 63,
      "gender": "Male",
      "first_name": "Wayne",
      "last_name": "Ramos",
      "email": "wramos1q@zimbio.com",
      "ip_address": "29.21.241.180"
    }, {
      "id": 64,
      "gender": "Male",
      "first_name": "Johnny",
      "last_name": "Rose",
      "email": "jrose1r@barnesandnoble.com",
      "ip_address": "93.0.128.4"
    }, {
      "id": 65,
      "gender": "Female",
      "first_name": "Phyllis",
      "last_name": "Welch",
      "email": "pwelch1s@tinypic.com",
      "ip_address": "254.115.22.157"
    }, {
      "id": 66,
      "gender": "Female",
      "first_name": "Jacqueline",
      "last_name": "Reyes",
      "email": "jreyes1t@github.io",
      "ip_address": "215.8.135.97"
    }, {
      "id": 67,
      "gender": "Female",
      "first_name": "Frances",
      "last_name": "Ellis",
      "email": "fellis1u@icq.com",
      "ip_address": "84.177.164.222"
    }, {
      "id": 68,
      "gender": "Female",
      "first_name": "Heather",
      "last_name": "Smith",
      "email": "hsmith1v@usatoday.com",
      "ip_address": "137.199.65.96"
    }, {
      "id": 69,
      "gender": "Male",
      "first_name": "Earl",
      "last_name": "Alexander",
      "email": "ealexander1w@blogtalkradio.com",
      "ip_address": "102.225.159.77"
    }, {
      "id": 70,
      "gender": "Female",
      "first_name": "Joyce",
      "last_name": "Gonzales",
      "email": "jgonzales1x@yellowbook.com",
      "ip_address": "51.162.204.173"
    }, {
      "id": 71,
      "gender": "Female",
      "first_name": "Melissa",
      "last_name": "Phillips",
      "email": "mphillips1y@ameblo.jp",
      "ip_address": "138.155.154.47"
    }, {
      "id": 72,
      "gender": "Female",
      "first_name": "Sharon",
      "last_name": "Jenkins",
      "email": "sjenkins1z@ted.com",
      "ip_address": "37.121.4.75"
    }, {
      "id": 73,
      "gender": "Male",
      "first_name": "Jonathan",
      "last_name": "Dixon",
      "email": "jdixon20@cbslocal.com",
      "ip_address": "57.47.10.45"
    }, {
      "id": 74,
      "gender": "Male",
      "first_name": "Kenneth",
      "last_name": "Washington",
      "email": "kwashington21@123-reg.co.uk",
      "ip_address": "189.209.117.69"
    }, {
      "id": 75,
      "gender": "Female",
      "first_name": "Helen",
      "last_name": "Dunn",
      "email": "hdunn22@pinterest.com",
      "ip_address": "77.172.237.109"
    }, {
      "id": 76,
      "gender": "Male",
      "first_name": "Chris",
      "last_name": "Jordan",
      "email": "cjordan23@blinklist.com",
      "ip_address": "135.148.97.93"
    }, {
      "id": 77,
      "gender": "Male",
      "first_name": "Larry",
      "last_name": "Marshall",
      "email": "lmarshall24@quantcast.com",
      "ip_address": "25.95.109.49"
    }, {
      "id": 78,
      "gender": "Female",
      "first_name": "Rebecca",
      "last_name": "Gonzales",
      "email": "rgonzales25@guardian.co.uk",
      "ip_address": "43.154.141.136"
    }, {
      "id": 79,
      "gender": "Female",
      "first_name": "Robin",
      "last_name": "Shaw",
      "email": "rshaw26@reuters.com",
      "ip_address": "236.82.145.147"
    }, {
      "id": 80,
      "gender": "Male",
      "first_name": "Kevin",
      "last_name": "Foster",
      "email": "kfoster27@4shared.com",
      "ip_address": "48.109.200.247"
    }, {
      "id": 81,
      "gender": "Male",
      "first_name": "Carl",
      "last_name": "Hunter",
      "email": "chunter28@soup.io",
      "ip_address": "197.82.85.12"
    }, {
      "id": 82,
      "gender": "Male",
      "first_name": "Wayne",
      "last_name": "Harris",
      "email": "wharris29@hexun.com",
      "ip_address": "140.144.44.11"
    }, {
      "id": 83,
      "gender": "Female",
      "first_name": "Elizabeth",
      "last_name": "Lewis",
      "email": "elewis2a@privacy.gov.au",
      "ip_address": "21.37.101.142"
    }, {
      "id": 84,
      "gender": "Female",
      "first_name": "Jessica",
      "last_name": "Reid",
      "email": "jreid2b@printfriendly.com",
      "ip_address": "92.22.13.248"
    }, {
      "id": 85,
      "gender": "Female",
      "first_name": "Stephanie",
      "last_name": "Evans",
      "email": "sevans2c@newsvine.com",
      "ip_address": "221.146.208.33"
    }, {
      "id": 86,
      "gender": "Male",
      "first_name": "Thomas",
      "last_name": "Mcdonald",
      "email": "tmcdonald2d@ebay.co.uk",
      "ip_address": "106.161.250.112"
    }, {
      "id": 87,
      "gender": "Female",
      "first_name": "Frances",
      "last_name": "Wright",
      "email": "fwright2e@csmonitor.com",
      "ip_address": "239.85.38.166"
    }, {
      "id": 88,
      "gender": "Male",
      "first_name": "Ernest",
      "last_name": "Olson",
      "email": "eolson2f@plala.or.jp",
      "ip_address": "187.181.229.100"
    }, {
      "id": 89,
      "gender": "Female",
      "first_name": "Jacqueline",
      "last_name": "Fowler",
      "email": "jfowler2g@behance.net",
      "ip_address": "171.240.179.55"
    }, {
      "id": 90,
      "gender": "Female",
      "first_name": "Evelyn",
      "last_name": "Snyder",
      "email": "esnyder2h@linkedin.com",
      "ip_address": "9.200.118.230"
    }, {
      "id": 91,
      "gender": "Male",
      "first_name": "Timothy",
      "last_name": "Romero",
      "email": "tromero2i@youku.com",
      "ip_address": "135.192.56.245"
    }, {
      "id": 92,
      "gender": "Male",
      "first_name": "Steve",
      "last_name": "Hayes",
      "email": "shayes2j@usda.gov",
      "ip_address": "151.240.197.190"
    }, {
      "id": 93,
      "gender": "Male",
      "first_name": "Roy",
      "last_name": "Campbell",
      "email": "rcampbell2k@foxnews.com",
      "ip_address": "72.23.13.212"
    }, {
      "id": 94,
      "gender": "Female",
      "first_name": "Maria",
      "last_name": "Taylor",
      "email": "mtaylor2l@weibo.com",
      "ip_address": "81.242.211.135"
    }, {
      "id": 95,
      "gender": "Male",
      "first_name": "David",
      "last_name": "Bryant",
      "email": "dbryant2m@nba.com",
      "ip_address": "14.114.44.206"
    }, {
      "id": 96,
      "gender": "Female",
      "first_name": "Amy",
      "last_name": "Jordan",
      "email": "ajordan2n@blogtalkradio.com",
      "ip_address": "213.227.66.148"
    }, {
      "id": 97,
      "gender": "Female",
      "first_name": "Debra",
      "last_name": "Castillo",
      "email": "dcastillo2o@newsvine.com",
      "ip_address": "229.106.117.175"
    }, {
      "id": 98,
      "gender": "Female",
      "first_name": "Tina",
      "last_name": "Carpenter",
      "email": "tcarpenter2p@wordpress.org",
      "ip_address": "202.142.63.51"
    }, {
      "id": 99,
      "gender": "Female",
      "first_name": "Lillian",
      "last_name": "Stone",
      "email": "lstone2q@qq.com",
      "ip_address": "164.227.140.171"
    }, {
      "id": 100,
      "gender": "Male",
      "first_name": "Albert",
      "last_name": "Cunningham",
      "email": "acunningham2r@purevolume.com",
      "ip_address": "120.59.95.207"
    }]; 
  }
}

module.exports = renderGridMockDataModule;